services:
  postgres:
    image: postgres:15
    container_name: tg-postgres
    restart: always

    environment:
      POSTGRES_DB: tg_db
      POSTGRES_USER: tg_user
      POSTGRES_PASSWORD: tg_pass

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - tg-network

  bot:
    build: .
    container_name: tg-bot
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tg_db
      - DB_USER=tg_user
      - DB_PASSWORD=tg_pass
      - USE_POSTGRES=true
    networks:
      - tg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: tg-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - tg-network

networks:
  tg-network:
    driver: bridge

volumes:
  pgdata:
